services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
      POSTGRES_DB: ${POSTGRES_DB:-jobhunter}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-app} -d ${POSTGRES_DB:-jobhunter}"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./backups:/backups

  db-backup:
    image: prodrigestivill/postgres-backup-local:16
    restart: unless-stopped
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: ${POSTGRES_DB:-jobhunter}
      POSTGRES_USER: ${POSTGRES_USER:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-app}
      # 03:00 UTC diariamente
      CRON_SCHEDULE: "0 3 * * *"
      POSTGRES_EXTRA_OPTS: "-Z9 -Fc -j 2"
    volumes:
      - ./backups:/backups
    depends_on:
      db:
        condition: service_healthy

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file: [.env]
    environment:
      PYTHONPATH: /work/src
    command:
      - bash
      - -lc
      - |
        alembic -c alembic.ini upgrade head && \
        exec uvicorn job_finder.api.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./:/work
    ports:
      - "${APP_PORT:-8000}:8000"

volumes:
  pg_data:
